### ISSUE TITLE
Consider making a stable release?

### ISSUE THREAD

**Issue by rwhogg** [Groovy-Emacs-Modes/groovy-emacs-modes#17]
Would you be willing to reconsider making a stable release? The Homebrew maintainers would appreciate it (see https://github.com/Homebrew/homebrew-emacs/pull/122) and it's also necessary to get groovy-mode into MELPA stable.

Thank you!

**Comment by russel** [comment]
To be honest I wasn't aware there was a MELPA Stable. Are there people using it?

In any event, given it exists the original rationale for only rolling release needs amendment, and this will help the Homebrew folk. I guess we must decide on a versioning consistent with semantic versioning. Also whether to put the version number in the source or just leave it as a Git tag.

A new MELPA recipe will be needed but that goes into the MELPA repository. Once we have a tag in place I will do the needful.

**Comment by rwhogg** [comment]
I don't know anyone personally who uses it, although https://stable.melpa.org/#/ claims there have been about 350,000 downloads to date.

**Comment by russel** [comment]
Ground is laid for a formal release, the question is how to do an RC type thing. I have made changes to the files which should trigger a MELPA rolling release. I will leave it a while and if there are no complaints I will tag the repository and create a MELPA Stable formula. Actually I shall do that last bit sooner rather than later.

**Comment by russel** [comment]
I think the time has come "to do something" rather than just cogitate. For now, until there is an alternative, files will continue to use ISO8601 date and time as the version number (which should be reasonably close to MELPA release numbers) and stable releases will be declared simply by tagging the repository with the appropriate tag. I shall do this now for this repository based solely on the fact that it hasn't changed for a while. We really need to get some tests in place!

**Comment by russel** [comment]
I have tagged the repository with v-1.0.0 so the rest is up to MELPA. I shall close this issue, feel free to reopen or raise a new issue if something fails to cause the MELPA Stable entry to be created.
