### ISSUE TITLE
MELPA doesn't list groovy-mode

### ISSUE THREAD

**Issue by warrenharris** [Groovy-Emacs-Modes/groovy-emacs-modes#21]
The readme describes how to use MELPA to load the groovy-mode, but groovy-mode does not appear in the list of packages.

**Comment by russel** [comment]
I had an outdated URL on the README, but it should still have worked.

If I go to http://melpa.org/ and type in groovy in the search box, I get the entry that if I follow gets to http://melpa.org/#/groovy-mode. So I am wondering what the problem was that you were seeing.

**Comment by savishy** [comment]
I believe the issue is with stable.melpa.org. I got confused as well; but basically it appears stable.melpa.org does not list any packages containing `groovy`. 
See screenshot:
![screenshot from 2016-03-30 09 11 43](https://cloud.githubusercontent.com/assets/13379978/14131309/939a623a-f657-11e5-8691-fe61cf704156.png)

**Comment by savishy** [comment]
So, to sum up: `melpa.org` lists `groovy-mode`, `stable.melpa.org` does not. 

![screenshot from 2016-03-30 09 14 46](https://cloud.githubusercontent.com/assets/13379978/14131352/ea555e18-f657-11e5-995c-6dea0e7bc2ff.png)

**Comment by russel** [comment]
There has been a v-1.0.0 tag which is what I understood would cause MELPA Stable to create a stable release, but this appears not to have happened.

**Comment by russel** [comment]
I have tagged the repository with 1.0.1, I am hoping this will generate an entry in MELPA Stable. Fingers crossed.

**Comment by russel** [comment]
Groovy Mode 1.0.1 now on MELPA Stable
